### ISSUE TITLE
[10.0] Can't relate an existing Partner to a Student

### ISSUE THREAD

**Issue by gustavovalverde** [openeducat/openeducat_erp#111]
If I have a Partner, or if I'm creating a new one, I should be able to select (on creation) if this partner is also an student. Otherwise, for companies working with high clients/students fluctuation and also using the CRM, is pointless as a bunch of duplication will occur.

Vice versa, creating a new student should allow me to match it to an existing partner.

**Comment by gustavovalverde** [comment]
Hi, we're willing to buy the Enterprise version of OpenEducat, but this is a deal-breaker feature if not available.

**Comment by parthivgls** [comment]
fixed in e896da9c22cb61ff577562e4ab7393c4230f245d
