### ISSUE TITLE
being both student and faculty

### ISSUE THREAD

**Issue by nehemiascr** [openeducat/openeducat_erp#125]
Good day, first I want to congratulate the team for such an amazing module :)

How can faculty be also student, meaning, how can the res.partner record of an op.faculty be same for a record in op.student, thanks

**Comment by siddharth-techreceptives** [comment]
@nehemiascr, To make faculty also student with same res.partner record

Create student and at bottom there is partner field where you can select existing partner record of that faculty.

Thanks.
