### ISSUE TITLE
ImportError: No module named 'openerp'

### ISSUE THREAD

**Issue by 5up3rD4n1** [openeducat/openeducat_erp#129]
I guess this is deprecate code

Here [subject_registration.py#L23](https://github.com/openeducat/openeducat_erp/blob/325bc3f88468f519d47c4800d9848f102adc823d/openeducat_core/models/subject_registration.py#L23)

**Comment by siddharth-techreceptives** [comment]
@5up3rD4n1 Thaks for suggestion, This issue is fixed in last PR.

Thanks.
