### ISSUE TITLE
Automaticaly create monthly fees for a course

### ISSUE THREAD

**Issue by fnegrini** [openeducat/openeducat_erp#130]
Acording to course value and honorary type, create fees for students of a class

**Comment by fnegrini** [comment]
@parthivgls 
Going further in the issue, theese are the enhancements that I am planning to do:
1. Create a new model for monthly fees wich will have the following attributes: class, student, fee therm line and period.
2. Create a view for this new model
2.1 Create subviews also in class and student form views
3. Create a wizard to automatic fill up all fees according to the period. Class and student could be used as filters
4. Create a wizard to create accounting related to all fee therms

Some considerations:

1. Fee therms may be enhanced to supply all information needed to create accounting correctly (Product for instance)
2. The accounting process an fees process are propositaly separated. This way will allow to create a single accounting for a student with all the classes fee therms
3. Each monthly fee will have a link to the accounting created (workflow)

Please check this ideas so that I can start the development.

**Comment by BIZ4Africa** [comment]
Hi,

coming a bit late, but this feature would be great!

Would even be better that those invoices takes the related period into the reference, instead of just the student name.

Regards,

**Comment by dip-suthar** [comment]
Hello, 

There is cronjob in a new update of Openeducat which will create fees invoice automatically based on the defined fees terms. 
We will come up with the other enhancement in future.

**Comment by BIZ4Africa** [comment]
Hello,

Is this enhancement commited yet?
I can't find it.
Regards
