### ISSUE TITLE
Create option to fill up of a class in an attendance list

### ISSUE THREAD

**Issue by fnegrini** [openeducat/openeducat_erp#131]
Create a button in attendance form wich fill up all students of the class

**Comment by siddharth-techreceptives** [comment]
@fnegrini Please check with latest code, we have wizard on attendance sheet for that.

To add students from wizard you can select absent students and confirm, other students are added automaticaly as present.

Thanks

**Comment by fnegrini** [comment]
Perfect! That's exactly what I need!!!
