### ISSUE TITLE
Install with demo.

### ISSUE THREAD

**Issue by crsilveira** [openeducat/openeducat_erp#15]
Exception: Module loading openeducat_erp failed: file openeducat_erp/demo/res.users.csv could not be processed:
 Line 1 : null value in column "name" violates not-null constraint
DETAIL:  Failing row contains (106, null, 1, null, null, 2015-01-26 15:27:30.628053, 0, \x6956424f5277304b47676f414141414e5355684555674141414c5141414143..., f, t, null, f, null, null, null, null, null, null, null, f, contact, null, null, null, pt_BR, null, 1, null, null, null, 2015-01-26 15:27:30.628053, null, null, 1, null, f, null, null, null, null, null, f, null, null, always, null, f, null, null, null, null, null, f).

**Comment by thomich** [comment]
what version of odoo do you use and what version of openeducat you cloned?
