### ISSUE TITLE
cannot find openeducat module/app in odoo 11

### ISSUE THREAD

**Issue by practicetestsforall** [openeducat/openeducat_erp#151]
I installed odoo 11 on windows and opened it on the browser, created a database and entered the portal with login details (administrator). I can only see 32 apps under apps. I tried searching for openeducat and found none. Under 'Users', --> 'Administrator'--> 'Access Rights' -  'Application Accesses', it says 'employee' and 'Settings' for Employees and Administration respectively. There is nothing else for me to try and find openeducat other than the search under apps. I tried the "developer mode" and it kicked me out completely from finding 'Apps'. So I had to create another database to enter the portal. I am a novice user and I am totally aware that I am doing something very wrong at a very basic level. please help.  Do i need to manually add the module? If so, where to I download it from? The instructions simply says to install odoo, search for openeducat and install it. I am stuck right at the searching for openeducat.

Thanks.

**Comment by ajaychauhan727** [comment]
How do you start your odoo server? Please check addons registered, probably you forgot to register OpenEducat repository in that.

**Comment by practicetestsforall** [comment]
Thanks for your reply. Odoo server starts automatically in the windows services (services.msc).  where can I  find the addons registration and the repository?
