### ISSUE TITLE
Create a new student, fee details not added

### ISSUE THREAD

**Issue by JavedShoukat** [openeducat/openeducat_erp#158]
Hi all, 
Please share how can i create new student and add fee collection details, i m using Odoo10.0, fee When i create student, 
 collection details are not included. Don't know why?

**Comment by dipesh-suthar-flectra** [comment]
Hello @JavedShoukat 

First, you have to create a course and relatively you have to create fees terms for that particular course under the Openeducat main menu. 

Assign fees term on a particular course and create student profile on which you have to assign course that system will create fees invoice according to Fees Terms. 

Thanks
