### ISSUE TITLE
Spanish translation?

### ISSUE THREAD

**Issue by usernamevth** [openeducat/openeducat_erp#159]
Hi, i work for an educational and formative public institute.
We are using OpenEduCat for Odoo 10. For us it is very important to translate the whole apps suite to Spanish, since the people we can read, speak, and write in english languaje can be counted with one hand (there are around 500 employes).

If there is not an oficcial current spanish translation, we could help to make that translation with all the proper documentation and support, we could even create documentation in spanish, because is a very important issue to us.

Waiting for your answer. Thanks.

**Comment by dipesh-suthar-flectra** [comment]
Hello @usernamevth 

Openeducat version 11.0 is available in Spanish language. 

Thanks
