### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zimbar** [openeducat/openeducat_erp#16]
Hello,

I have this error on module installation

raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: openeducat_erp.model_op_student" while parsing /opt/odoo/bizappdev/openeducat_erp/security/op_security.xml:23, near
<record model="ir.rule" id="student_login_rule">
			<field name="name">Student Login rule</field>
			<field name="model_id" ref="model_op_student"/>
			<field name="groups" eval="[(4, ref('openeducat_erp.group_op_student'))]"/>
			<field name="domain_force"> [('user_id','=',user.id)]</field>
		</record>

Thanks

**Comment by parthivgls** [comment]
which branch you are using and which revision of odoo you are using. I am unable to reproduce the bug on OpenEduCat : 8.0 branch with Odoo v8.0
