### ISSUE TITLE
Print Exam And Assignment Results

### ISSUE THREAD

**Issue by cbanegas** [openeducat/openeducat_erp#164]
Hi. This isn't really a bug, but is there a way to print exam and assigment marks/grades/results?

**Comment by dipesh-suthar-flectra** [comment]
Hello @cbanegas 

You can generate student marksheet under exam module and in enterprise version dashboard is available, In version 11.0 there is no assignment report with marks but in future, we will add some more reports (in enterprise version).

Thanks
