### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by aman-gautam** [openeducat/openeducat_erp#17]
Almost all the models extend openerp.osv.osv which is deprecated. Instead of it, openenp.model.Model should be used. 

Following line in `osv.py` file is making the current code run fine.

	# Deprecated, kept for backward compatibility.
	osv = Model
	osv_memory = TransientModel
	osv_abstract = AbstractModel # ;-)

But it should be updated to extend Model class. For new odoo developers `osv` is confusing.

**Comment by parthivgls** [comment]
Yes but it is still backward compatible, we are working on migrating the entire code base to new API of v9.
