### ISSUE TITLE
Can't add students to a class

### ISSUE THREAD

**Issue by mprice4-1Up** [openeducat/openeducat_erp#178]
For our business model, I can't figure out how to add students to a course.

Our business is setup such as this:

- Course (Beginner English, Intermediate English, etc.)
- Batch (Beginner English Monday 5-6, Beginner English Monday 7-8, etc.)
- Session (Week 1 - Week 18 according to the timing) 

Course has a 1 to many relationship to batches; Batch has a 1 to many relationship to Sessions. 

After reading the documentation there doesn't seem to be a way to add students to a course, batch or session...is there? (I did notice you add faculty to the session)

**Comment by yk134** [comment]
Hi @mprice4-1Up,
Can you tell me on which branch/version (means 11.0 or 12.0) you are ??

**Comment by mprice4-1Up** [comment]
Hi, yk134,

I'm using branch 11, the community version. 

Thanks in advance,
-Matt

**Comment by dipesh-suthar-flectra** [comment]
Hello @mprice4-1Up 

Using admission process you can add student under a particular course and batch. Use openeducat_admission module. 
please check https://www.youtube.com/watch?v=ElmZN65L978

Thanks
