### ISSUE TITLE
OpenEduCat tab is not visible

### ISSUE THREAD

**Issue by VimalRughani** [openeducat/openeducat_erp#18]
Hi,
I have installed odoo using bitnami installer, after that I download and installed OpenEduCat from https://apps.openerp.com/apps/modules/8.0/openeducat_erp/

Even After installation of that I didn't find any tab for OpenEduCat or Configuration tab which should there accordingly to official document. https://media.readthedocs.org/pdf/openeducat/latest/openeducat.pdf

Please guide how to handle this situation.
![openeducat_8](https://cloud.githubusercontent.com/assets/6803941/7586911/6f761b82-f8cf-11e4-9346-da72e0f5183b.png)

**Comment by parthivgls** [comment]
Go to users and assign proper access rights.

**Comment by VimalRughani** [comment]
Thanks Parthiv for quick response.
