### ISSUE TITLE
Online Admission

### ISSUE THREAD

**Issue by vsila** [openeducat/openeducat_erp#180]
Does anyone know how to get online admissions or automate the process of online applications so that the data entered through the website will go straight to the admission registers?

**Comment by yk134** [comment]
Hi @vsila 

See this video for [Online Admission](https://www.youtube.com/watch?v=OPY5xVOOg7M)
and you can also have many other tutorials videos for [OpenEduCat](https://www.youtube.com/channel/UC7HLHTgfsOTE-ueRVNZ4Avg/videos) over here.
