### ISSUE TITLE
[12.0] Wrong avatar.png location in faculty/student kanban views

### ISSUE THREAD

**Issue by timotalvitie** [openeducat/openeducat_erp#183]
Hi, I stumbled upon the following small issue while importing some faculty test data: 

The default avatar image does not load in faculty and student kanban views, it seems to be because the avatar.png file has moved in Odoo 12.0 from base/static/src/img/avatar.png to base/static/img/avatar.png

Affected lines:
https://github.com/openeducat/openeducat_erp/blob/12.0/openeducat_core/views/faculty_view.xml#L19
https://github.com/openeducat/openeducat_erp/blob/12.0/openeducat_core/views/student_view.xml#L20

**Comment by yk134** [comment]
Hi @timotalvitie 
Please take a pull for updated code [2a3df54e8d623c7e3bc6fa7cdd518b94f3700799](https://github.com/openeducat/openeducat_erp/commit/2a3df54e8d623c7e3bc6fa7cdd518b94f3700799)
