### ISSUE TITLE
Prefill attendance form with students details

### ISSUE THREAD

**Issue by aman-gautam** [openeducat/openeducat_erp#19]
The one2many field of [attendance_sheet](https://github.com/openeducat/openeducat_erp/blob/8.0/openeducat_erp/op_attendance_sheet/op_attendance_sheet.py) should automatically be filled up with the list of students on the onchange event of register_id. 

Since register_id, already has division_id which can directly be mapped to students.

**Comment by paulJordaan** [comment]
Hi, also came across this issue. @aman-gautam  did you manage to fix this?

**Comment by aman-gautam** [comment]
@paulJordaan Did not quite get time to do that. Will give it a try over the weekend.

**Comment by jacksolutions** [comment]
any update on it?

**Comment by jacksolutions** [comment]
@aman-gautam any update on this issue?

**Comment by parthivgls** [comment]
==> Its working properly. To have this you should follow steps as below:
1> Go to Attendance Sheet form view & click on More.
2> Select Attendance Sheet Import, One wizard will open.
3> Add students who are absent.
4> Click on "Confirm Student Selection".

**Comment by amet123** [comment]
but good way is when we create a sheet all student show as present just click absent student and finish work
