### ISSUE TITLE
Generate sessions timing bugged

### ISSUE THREAD

**Issue by anmolsahoo25** [openeducat/openeducat_erp#190]
Hi,

In the TimeTable module when I use the Generate Sessions feature, the timing displayed in the calendar is wrong. Could someone point me to the code section where this is happening, so that I can attempt a fix?

**Comment by yk134** [comment]
Hi @anmolsahoo25 ,
Did you set your timezone?
If yes, and still get an issue, please share some screenshots or give more details for it.

**Comment by anmolsahoo25** [comment]
Hey! I got it fixed. The timezone on my Odoo server instance was wrong! Thank you so much. Sorry for the spurious issue.
