### ISSUE TITLE
Generate Sessions timing spans multiple days

### ISSUE THREAD

**Issue by mprice4-1Up** [openeducat/openeducat_erp#195]
When generating sessions it spans multiple days instead of 1 hour. See attached screen shots.

Please advise. Thanks in advance!
![img_0265](https://user-images.githubusercontent.com/38380835/49347945-54759f00-f6dd-11e8-91bf-8dcb014a1407.png)
![img_0266](https://user-images.githubusercontent.com/38380835/49347949-59d2e980-f6dd-11e8-846b-07e76c60f2ee.png)
![img_0267](https://user-images.githubusercontent.com/38380835/49347950-5ccdda00-f6dd-11e8-8575-f1dd288b926d.png)
[](url)

**Comment by dip-suthar** [comment]
Hello @mprice4-1Up 
The issue you have posted is not reproducible [ Do not forget to set proper timezone]
I guess you have customized the timetable session form. So please check from your code OR provide some more details about it. 

Thanks
