### ISSUE TITLE
In Issue Book, Student and Library card should be calculated

### ISSUE THREAD

**Issue by aman-gautam** [openeducat/openeducat_erp#21]
While issuing a book to a student, the librarian should have to fill up only the library card and Student field should be readonly + computed by the server.

Steps:
1. Login as librarian
2. Goto Library -> Book -> Select a book -> Issue Book

[Actual]
Librarian needs to enter both library card and student name.

[Expected]
Librarian should have to fill up only the library card and the student name should show up onchange. This will make sure that there is less margin of human error of selecting a student and someone else's card.

![issue22](https://cloud.githubusercontent.com/assets/3582748/7648828/c27e5ce0-fb04-11e4-9c55-2ef7b32fd106.png)

**Comment by ajaychauhan727** [comment]
Solved in release v9.0.2.2.0.
