### ISSUE TITLE
Issue individual books 

### ISSUE THREAD

**Issue by aman-gautam** [openeducat/openeducat_erp#22]
Even if there are 5 books available and only one book is issued, the librarian cannot issue more books.

Steps:
1. Login as librarian
2. Library -> Book -> Issue book -> {Fill up the form} and issue the book.

[Actual]
Even if you issue 2 books and 5 are presently available, there in no option to issue the rest of the books. 

[Expected]
There should be a button to return book and another to issue more (which should be disabled if no more books are available).

![issue21a](https://cloud.githubusercontent.com/assets/3582748/7648997/6f668bca-fb06-11e4-94c7-dc164071871e.png)

**Comment by ajaychauhan727** [comment]
Solved in latest release.
