### ISSUE TITLE
Creating new student does not create a new user

### ISSUE THREAD

**Issue by aman-gautam** [openeducat/openeducat_erp#24]
Documentation on adding a new faculty, student or any other res.partner is missing. It takes several steps to add a new user from a faculty. This step should either by completely automated or documented. Current [documentation](http://databit-openeducat.readthedocs.org/en/latest/faculty.html) just has a screenshot that tells nothing.

**Comment by aman-gautam** [comment]
Steps for creating a faculty that can log in are:

1. Goto Faculty -> Create and create a new faculty
2. Open the form view of the Employee (click on the picture in kanban view)
3. Click on create employee button
4. Click on the link next to **Employee** field
5 Click on Edit 
6. Set a related user (create a new user)
7. Go to Settings -> Users
8. Click on the user just created
9. Click on edit and add enable the faculty checkbox.

It doesn't look like the best UX to me. If there is an easier way, it should be documented.

**Comment by parthivgls** [comment]
==> To create an user for student, we have steps as following:
    1> Go to List view of Students
    2> Select the student you want to create user for
    3> Click on More & select Create Users
    4> One Wizard will open, click on Create Users button.
Now to create user for Faculty, You should follow the basic steps as we do to create user for employee.
