### ISSUE TITLE
create users button not display

### ISSUE THREAD

**Issue by kartikdanidhariya** [openeducat/openeducat_erp#39]
I use openeducat in openerp 
i watched this video https://www.youtube.com/watch?v=4C7sOS_wCM8

1> Go to List view of Students
2> Select the student you want to create user for
3> Click on More & select Create Users

but in my installed openeducat there is no any "create user" option
how can i get this button

**Comment by ajaychauhan727** [comment]
The video you mentioned in link is for "Managing the Faculty Profile"
Please check this video https://www.youtube.com/watch?v=AlX80786Qag

Can't reproduce it. Please check access rights for the user.

**Comment by kartikdanidhariya** [comment]
can you please specify which access rights are needed
