### ISSUE TITLE
Access rights for OpenEducat

### ISSUE THREAD

**Issue by kartikdanidhariya** [openeducat/openeducat_erp#42]
Hi,
 i asked question #39 
and you provide video link i see that , after you say that access rights are required.
can you please specify that which access rights are required 

for admin user in odoo access rights are shown in below image

![access_rights_admin_1](https://cloud.githubusercontent.com/assets/9051467/9304137/a06a5f94-4502-11e5-8e91-8d60f0f99947.png)

from user i also uploaded image for access rights

![user_admin](https://cloud.githubusercontent.com/assets/9051467/9304172/00c24bcc-4503-11e5-850a-fc8cf940a5be.png)

Any other rights are required so please specify
Please help
Thanks in advanced!!!

**Comment by kartikdanidhariya** [comment]
I think the problem is cache ,
so how can we clear cache in odoo for openeducat

**Comment by kartikdanidhariya** [comment]
I think the problem is version of openeducat
my current version is 1.0

**Comment by ajaychauhan727** [comment]
It's not reproducible.
