### ISSUE TITLE
Install failed on odoo 9

### ISSUE THREAD

**Issue by codeadict** [openeducat/openeducat_erp#44]
On Odoo version 9 its failing the install in **op_faculty/op_faculty.py** on line 55:

```
    last_login = fields.Date(
        'Latest Connection', related='partner_id.user_id.login_date',
        readonly=1)
```

It should be like this to work:

```
    last_login = fields.Datetime(
        'Latest Connection', related='partner_id.user_id.login_date',
        readonly=1)
```

**Comment by ajaychauhan727** [comment]
We haven't add our branch for odoo 9.0 is still not released. We will release OpenEduCat v9, once odoo release 9.0.

**Comment by codeadict** [comment]
ok great @ajaychauhan727 i made it worknow, i can contribute with this branch

**Comment by parthivgls** [comment]
@codeadict : Thank you for your efforts, you can surely contribute but as of now we are refactoring OpenEduCat code, new code will be out soon.
