### ISSUE TITLE
Request to make constraints optional

### ISSUE THREAD

**Issue by LordRatte** [openeducat/openeducat_erp#516]
This commit broke my clients workflow. Do you mind if I create a pull request to make these constraints optional? Some of them are arbitrary and don't need to be enforced on every system.

https://github.com/openeducat/openeducat_erp/blame/b1d516167320a878fbc06192ea72991ae7761f4a/openeducat_timetable/models/timetable.py#L119

**Comment by parthivgls** [comment]
they are optional now from https://github.com/openeducat/openeducat_erp/commit/703425f2315867e261c7d55602bc3fa975fdc70f
