### ISSUE TITLE
Attendance missing key feature

### ISSUE THREAD

**Issue by KelvinMW** [openeducat/openeducat_erp#533]
From this repository auto "create" is not showing in local, is that a bug? I did not see this missing feature in enterprise vs community edition. 

local machine: 

![image](https://user-images.githubusercontent.com/14296120/121808646-32701680-cc62-11eb-8421-d3f772c78b58.png)

demo:
![image](https://user-images.githubusercontent.com/14296120/121808503-7ca4c800-cc61-11eb-8024-193ef7372ce8.png)

**Comment by parthivgls** [comment]
auto create is an enterprise feature.
