### ISSUE TITLE
DOCUMENT VIEW

### ISSUE THREAD

**Issue by KelvinMW** [openeducat/openeducat_erp#555]
Allow me to ask:
in student portal is document view exclusively part of the enterprise version? 
In community version setup with all documents rights given, a student login view to documents looks like this:
![image](https://user-images.githubusercontent.com/14296120/123774440-1319f000-d8d6-11eb-97b8-216d634fdc93.png)
Thats a sample invoice from account module

The profile has active activities as :
![image](https://user-images.githubusercontent.com/14296120/123776844-583f2180-d8d8-11eb-9f8c-e5f191d0cb6e.png)

Is openeducat the document view out of the box when using enterprise edition only?
activities from openeducat are not visible in document view section.

**Comment by parthivgls** [comment]
Yes, it is only available in enterprise edition only
