### ISSUE TITLE
Student fail one subject

### ISSUE THREAD

**Issue by RocioLetona** [openeducat/openeducat_erp#618]
Hi!

I have two interrelated questions.

-First, how can configure two calls for one subject?
-Second, how can configure on 14.0 version the grade scale and the grade template if the course have two call for subject?

I mean, the studet fail the first call so we can't compute his first grade for the final grade, we must compute the grade of the secod call.

It is possible to configure?

Can sameone explain me. 

Thanks all!

**Comment by Aditya04-code** [comment]
hey! can u please elaborate on the "two calls" you are talking about
