### ISSUE TITLE
OpenEduCat mobile app

### ISSUE THREAD

**Issue by lakshman12345** [openeducat/openeducat_erp#65]
OpenEduCat mobile app not connecting to odoo9 is there any chance of keeping the openeducat android repository  in github

**Comment by siddharth-techreceptives** [comment]
Upgradation is in progress, You will be notify when its done.

**Comment by lakshman12345** [comment]
Hi siddharth i am using your openedu cat mobile app and we are connecting it with openeducat which is devoloped from your open source python code now in mobile app timetable is not synchronising can you help me with that
