### ISSUE TITLE
Online Admision in community version?

### ISSUE THREAD

**Issue by afols** [openeducat/openeducat_erp#659]
Hi
I am configuring OpenEducat for the first time.
I have had no problems except with the Admission process.

I can't get the Online Registration page to appear on the Web.

I have seen the videos. (tuttorials)
I have started an admission process (which is current)
However, the link to the form does not appear on the Web.

**My Settings:**
odoo 16
OpenEduCat 16
Host: VPS at https://clients.cloudclusters.io/

I would appreciate any help
Adrian

**Comment by parthivgls** [comment]
Online admission is part of OpenEduCat Enterprise Edition.

**Comment by agrogers** [comment]
What are the differences between Enterprise and standard versions? Is there a document describing it somewhere?
