### ISSUE TITLE
After ugrading, same problem, impossible to add subject to course

### ISSUE THREAD

**Issue by fgarcia-humanoide** [openeducat/openeducat_erp#708]
I updated new code, but same results

root@testschool-odoo16-01:/data/compose/5/addons/openeducat_erp# git pull
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 134 (delta 83), reused 123 (delta 81), pack-reused 0
Receiving objects: 100% (134/134), 74.15 KiB | 14.83 MiB/s, done.
Resolving deltas: 100% (83/83), completed with 51 local objects.
From https://github.com/openeducat/openeducat_erp
   42e4256c..b57dfea4  16.0       -> origin/16.0
   99614931..366760af  14.0       -> origin/14.0
   190d7484..3d9ef097  15.0       -> origin/15.0
   55987be7..6e57dfe3  2.0        -> origin/2.0
Updating 42e4256c..b57dfea4
Fast-forward
 openeducat_admission/demo/admission_demo.xml        |   5 +++++
 openeducat_admission/models/admission_register.py   |   2 +-
 openeducat_assignment/demo/assignment_demo.xml      |   5 +++++
 openeducat_attendance/demo/attendance_line_demo.xml |   5 +++++
 openeducat_core/__manifest__.py                     |   2 ++
 openeducat_core/models/faculty.py                   |   2 ++
 openeducat_core/models/res_company.py               |   1 +
 openeducat_core/static/src/img/g2.webp              | Bin 0 -> 7486 bytes
 openeducat_core/static/src/js/g2_review.js          |  44 ++++++++++++++++++++++++++++++++++++++++++++
 openeducat_core/static/src/scss/style.scss          |  26 ++++++++++++++++++++++++++
 openeducat_core/static/src/xml/review.xml           |  27 +++++++++++++++++++++++++++
 openeducat_core/views/faculty_view.xml              |   8 ++++----
 openeducat_core/views/student_view.xml              |   8 ++++----
 openeducat_exam/demo/exam_demo.xml                  |   5 +++++
 openeducat_fees/demo/student_fees_details_demo.xml  |   5 +++++
 openeducat_timetable/demo/op_timetable_demo.xml     |   5 +++++
 16 files changed, 141 insertions(+), 9 deletions(-)
 create mode 100644 openeducat_core/static/src/img/g2.webp
 create mode 100644 openeducat_core/static/src/js/g2_review.js
 create mode 100644 openeducat_core/static/src/xml/review.xml
root@testschool-odoo16-01:/data/compose/5/addons/openeducat_erp#

**Comment by parthivgls** [comment]
have you upgraded openeducat core module from apps ?

**Comment by fgarcia-humanoide** [comment]
I have upraded it doing git pull to github repository
-------------------------------------------------------------------
Fernando Garcia Hansen
Economista nº 991 PO

*Humanoide Servicios para la Pyme, S.L.N.E.*
*Teléfono 657 054 861*

*https://calendly.com/humanoide/soporte-odoo
<https://calendly.com/humanoide/soporte-odoo>*
www.humanoide.es






Este mensaje y sus archivos adjuntos van dirigidos exclusivamente a su
destinatario, pudiendo contener información confidencial sometida a secreto
profesional. No está permitida su reproducción o distribución sin la
autorización expresa de HUMANOIDE SERVICIOS PARA LA PYME, S.L.N.E.. Si
usted no es el destinatario final por favor elimínelo e infórmenos por esta
vía.
Sus datos de carácter personal han sido recogidos de acuerdo con lo
dispuesto en el Reglamento (UE) 2016/679 del Parlamento Europeo y del
Consejo, de 27 de abril de 2016, relativo a la protección de las personas
físicas en lo que respecta al tratamiento de datos personales y a la libre
circulación de los mismos.
Le ponemos en conocimiento que estos datos se encuentran almacenados en un
fichero propiedad de HUMANOIDE SERVICIOS PARA LA PYME, S.L.N.E. De acuerdo
con la Ley anterior, tiene derecho a ejercer los derechos de acceso,
rectificación, cancelación, limitación, oposición y portabilidad de manera
gratuita mediante correo electrónico a: ***@***.*** o bien en la
dirección: C/ Tomás A. Alonso, 193 2ºA, 36208 Vigo (Pontevedra).
Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo
electrónico a la siguiente dirección: ***@***.***

**Comment by parthivgls** [comment]
restarted the server and upgraded the apps ??

**Comment by fgarcia-humanoide** [comment]
yes
-------------------------------------------------------------------
Fernando Garcia Hansen
Economista nº 991 PO

*Humanoide Servicios para la Pyme, S.L.N.E.*
*Teléfono 657 054 861*

*https://calendly.com/humanoide/soporte-odoo
<https://calendly.com/humanoide/soporte-odoo>*
www.humanoide.es






Este mensaje y sus archivos adjuntos van dirigidos exclusivamente a su
destinatario, pudiendo contener información confidencial sometida a secreto
profesional. No está permitida su reproducción o distribución sin la
autorización expresa de HUMANOIDE SERVICIOS PARA LA PYME, S.L.N.E.. Si
usted no es el destinatario final por favor elimínelo e infórmenos por esta
vía.
Sus datos de carácter personal han sido recogidos de acuerdo con lo
dispuesto en el Reglamento (UE) 2016/679 del Parlamento Europeo y del
Consejo, de 27 de abril de 2016, relativo a la protección de las personas
físicas en lo que respecta al tratamiento de datos personales y a la libre
circulación de los mismos.
Le ponemos en conocimiento que estos datos se encuentran almacenados en un
fichero propiedad de HUMANOIDE SERVICIOS PARA LA PYME, S.L.N.E. De acuerdo
con la Ley anterior, tiene derecho a ejercer los derechos de acceso,
rectificación, cancelación, limitación, oposición y portabilidad de manera
gratuita mediante correo electrónico a: ***@***.*** o bien en la
dirección: C/ Tomás A. Alonso, 193 2ºA, 36208 Vigo (Pontevedra).
Si usted no desea recibir nuestra información, póngase en contacto con
nosotros enviando un correo
electrónico a la siguiente dirección: ***@***.***

**Comment by fgarcia-humanoide** [comment]
![subject](https://github.com/openeducat/openeducat_erp/assets/7599709/8cac62ba-a09a-421a-8e49-fcc5449662c3)
cannot add subject to course

**Comment by parthivgls** [comment]
fixed in https://github.com/openeducat/openeducat_erp/pull/721
