### ISSUE TITLE
Unable to setup Openeducat in the ubuntu system

### ISSUE THREAD

**Issue by pimcoreanand** [openeducat/openeducat_erp#760]
Hi,

I am unable to download and install Openeducat on the Ubuntu system.

Can you help here with the steps to setup on my server?

Thanks,

**Comment by ak120591** [comment]
Whats your ubuntu version?
Any logs or screenshots of error would help find the issue.

**Comment by pimcoreanand** [comment]
Ubuntu latest version 22.04
Could you please share steps or documentation to install Openeducat

**Comment by pimcoreanand** [comment]
Kindly find the error which I am getting copying



(myenv) ubuntu@ip-172-31-85-221:~/openeducat_erp$ sudo cp conf/oeconf.py.sample conf/oeconf.py
cp: cannot stat 'conf/oeconf.py.sample': No such file or directory
