### ISSUE TITLE
lms issue

### ISSUE THREAD

**Issue by yasseribrahim740** [openeducat/openeducat_erp#763]
Hello i have lms app on odoo 15 self hosted ,when i want to add new course this error appear in old odoo15 releases (AttributeError: module 'odoo.tools' has no attribute 'email_normalize_all')
and when i use latest of odoo 15 this error appear (TypeError: cannot substract different models: 'res.partner()' and 'res.users()') also this error now in your demo , how can i solve it

**Comment by parthivgls** [comment]
LMS is openeducat enterprise app, you need to report the issue with your order details on enterprise support form.
