### ISSUE TITLE
Addmission register dropdown shows only about 100 records

### ISSUE THREAD

**Issue by ThreatFree** [openeducat/openeducat_erp#778]
I am trying to increase the records of the drop down Addmission register
<img width="1243" alt="Screenshot 2024-07-26 at 8 43 57 AM" src="https://github.com/user-attachments/assets/3870166f-b318-4389-a2eb-76393ea5f10f">

any suggestion ?

**Comment by parthivgls** [comment]
looks like not the current version in use.
