### ISSUE TITLE
Unable to change Settings 

### ISSUE THREAD

**Issue by n3wang** [openeducat/openeducat_erp#780]
I am hosting OpenEduCat within a Odoo Docker container. I installed OpenEduCat by adding it to the addons folder by unloading the zip file with all the folders. and then installed it via the apps dashboard.

![image](https://github.com/user-attachments/assets/b641d997-fa14-4e26-b5a9-77293b30d085)

My odoo Containers installation:

```
docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db_latest postgres:15


docker run -p 8069:8069 --name odoo --link db_latest:db -t odoo
```

When I attempt to change the settings, I encounter an issue: after clicking "Save," a brief error window flashes, and the settings are not saved.

![openeducat](https://github.com/user-attachments/assets/112c743f-8117-4b04-9e16-85e39e48258c)

I am able to change settings outside of Openeducat:

![cansave](https://github.com/user-attachments/assets/64c6ef76-4fdb-4628-8dd5-00203130afaa)

Is this normal? What can I do to fix it? Have I missed a step?

My applications: Base Odoo applications that comes by default activated + Openeducat modules:
<img width="1764" alt="image" src="https://github.com/user-attachments/assets/e8b4dcfb-dfb8-46da-b557-e9ecb4786613">

**Comment by parthivgls** [comment]
Module names in the list with "?" next to it are OpenEduCat Enterprise Edition Modules, which are only available upon purchase.

**Comment by n3wang** [comment]
@parthivgls 
> Module names in the list with "?" next to it are OpenEduCat Enterprise Edition Modules, which are only available upon purchase.

Thank you for responding.
The same happens the same with `non ? next to them` modules. Or all settings can only be enabled at enterprise only?

![screen_settings_non](https://github.com/user-attachments/assets/c8746365-1371-4e8c-8020-aef34c2fec0e)

Another Question: Will the one time payment suffice for the paid enterprise version?

**Comment by paulomesquitas** [comment]
I have the same problem. Same installation but can't save changes in OpenEducat settings. For none function
