### ISSUE TITLE
Upgrade between version

### ISSUE THREAD

**Issue by jpoa** [openeducat/openeducat_erp#817]
Greetings,
I have a question regarding openeducat that I am unable to find anywhere. How are the upgrades between versions handled for the community edition?

Ie, between v16 and v17, how is this processed? Is it with OpenUpgrade and then just update the modules from openeducat? What about model changes in openeducat?

Thanks in advance!

**Comment by parthivgls** [comment]
you need to write your own openupgrade script for update for the community edition.
