### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by TecSecret** [openeducat/openeducat_erp#82]
Good evening,

First, I want to congratulate the module.

How can I add a new language? For I tried through a .po file and it did not translate.

Can you tell me the documentation for it?

From already thank you very much

Att
Nelsir Luterek

---

Boa noite,

Em primeiro lugar, quero parabenizar pelo módulo.

Como posso adicionar um novo idioma? Pois tentei através de um arquivo .po e o mesmo não traduziu.

Pode me informar a documentação para isso?

Desde já muito obrigado

Att
Nelsir Luterek

**Comment by parthivgls** [comment]
@TecSecret you can always add other languages using .po files. for more you can follow this documentation https://www.odoo.com/documentation/10.0/reference/translations.html
