### ISSUE TITLE
Ask for openducat version 10

### ISSUE THREAD

**Issue by W360S** [openeducat/openeducat_erp#93]
Hello i want to ask do you have plan to upgrade version 9 to version 10?
i have odoo 10 but really interested about your projects

**Comment by ajaychauhan727** [comment]
Yes, we are working on it. You will find version 10 with new & enhanced features shortly.

**Comment by W360S** [comment]
Do you have dealine for this?

**Comment by parthivgls** [comment]
new v10 will be out by 25th December 2016.

**Comment by W360S** [comment]
Thank you ☺ and congrate to you project ☺ I will waiting
